apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pos

labels:
  - includeSelectors: true
    pairs:
      app: pos

resources:
  - namespace.yaml
  - service.yaml
  - ingress.yaml
  - deploy.yaml

images:
  - name: docker.io/library/pos
    newTag: 0.4.0
