apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: beverage-buzz

labels:
  - includeSelectors: true
    pairs:
      app: beverage-buzz

resources:
  - namespace.yaml
  - service.yaml
  - ingress.yaml
  - deploy.yaml

images:
  - name: docker.io/library/beverage-buzz
    newTag: 0.4.0
