apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: config

labels:
  - includeSelectors: true
    pairs:
      app: config

resources:
  - namespace.yaml
  - service.yaml
  - ingress.yaml
  - deploy.yaml

images:
  - name: docker.io/library/config
    newTag: 0.4.0
